### ISSUE TITLE
Filter query doesn't work for PHP

### ISSUE THREAD

**Issue by Shyam0307** [kontent-ai/delivery-sdk-php#116]
$items = $this->client->getItems((new QueryParams())
        ->in('system.type', 'article','project'));

Filter query for multiple system type is giving only an first item response . 

![Screenshot_2](https://user-images.githubusercontent.com/20546115/203034245-952c1329-7afd-47bd-9239-dfff7f9319d9.png)

**Comment by Simply007** [comment]
Hello @Shyam0307,

thanks for submitting the issue.

Could you verify that all of the items you expect are already published (assuming you are using the client pointing to [published content](https://github.com/kontent-ai/delivery-sdk-php#previewing-unpublished-content))? 

Could you provide the project ID with the items, so that we can check whether the issue is routing from SDK, or from the API itself?

Or could you provide the result of the GET request to URL: `https://deliver.kontent.ai/<PROJECT-ID>/items?system.type[in]=article,project` so that it is possible to compose the test?

**Comment by Simply007** [comment]
Hi!

This issue has gone quiet. 👻
It’s been a while since the last update here.

If we missed anything on this issue or if you want to keep it open, please reply here. 

Thanks for being a part of the Kontent.ai community!
